openapi: 3.0.2
info:
  version: 1.0.0
  title: API de gestion de collection de films
  description: API REST pour gérer une collection personnelle de films avec statuts, notes et avis
  contact:
    name: "Votre Nom"
    email: votre.email@example.com
servers:
- url: http://localhost:3000/api
  description: Serveur de développement local
paths:
  /movies:
    get:
      tags:
      - Film
      summary: Liste tous les films de la collection
      parameters:
      - $ref: '#/components/parameters/pageParam'
      - $ref: '#/components/parameters/limitParam'
      - name: status
        in: query
        description: Filtre par statut (a_voir, vu, en_cours)
        required: false
        schema:
          type: string
          enum: [a_voir, vu, en_cours]
      - name: genre
        in: query
        description: Filtre par genre
        required: false
        schema:
          type: string
      - name: sort
        in: query
        description: Trier par (date_ajout, note, annee, titre)
        required: false
        schema:
          type: string
          enum: [date_ajout, note, annee, titre]
          default: date_ajout
      - name: order
        in: query
        description: Ordre de tri (asc, desc)
        required: false
        schema:
          type: string
          enum: [asc, desc]
          default: desc
      responses:
        "200":
          description: Une collection de films est retournée
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Nombre total de films
                  page:
                    type: integer
                    description: Page courante
                  limit:
                    type: integer
                    description: Nombre de films par page
                  movies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Movie'
    post:
      tags:
      - Film
      summary: Ajoute un nouveau film à la collection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieInput'
      responses:
        "201":
          description: Le film a été ajouté avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        "400":
          description: Données invalides

  /movies/{id}:
    get:
      tags:
      - Film
      summary: Récupère les détails d'un film spécifique
      parameters:
      - name: id
        in: path
        description: L'identifiant unique du film
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Un film est retourné
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        "404":
          description: Le film n'existe pas
    put:
      tags:
      - Film
      summary: Met à jour les informations d'un film
      parameters:
      - name: id
        in: path
        description: L'identifiant unique du film
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieInput'
      responses:
        "200":
          description: Le film a été mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        "404":
          description: Le film n'existe pas
        "400":
          description: Données invalides
    delete:
      tags:
      - Film
      summary: Supprime un film de la collection
      parameters:
      - name: id
        in: path
        description: L'identifiant unique du film
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Le film a été supprimé avec succès
        "404":
          description: Le film n'existe pas

  /movies/search:
    get:
      tags:
      - Film
      summary: Recherche des films par titre
      parameters:
      - name: q
        in: query
        description: Terme de recherche
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/pageParam'
      - $ref: '#/components/parameters/limitParam'
      responses:
        "200":
          description: Résultats de la recherche
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  movies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Movie'

  /stats:
    get:
      tags:
      - Statistiques
      summary: Récupère les statistiques de la collection
      responses:
        "200":
          description: Statistiques de la collection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'

  /genres:
    get:
      tags:
      - Genre
      summary: Liste tous les genres disponibles dans la collection
      responses:
        "200":
          description: Liste des genres
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    genre:
                      type: string
                    count:
                      type: integer
                      description: Nombre de films dans ce genre

components:
  schemas:
    MovieInput:
      type: object
      required:
        - titre
        - annee
      properties:
        titre:
          type: string
          description: Titre du film
          example: "Inception"
        annee:
          type: integer
          description: Année de sortie
          example: 2010
        realisateur:
          type: string
          description: Nom du réalisateur
          example: "Christopher Nolan"
        genres:
          type: array
          items:
            type: string
          description: Liste des genres
          example: ["Science-Fiction", "Thriller"]
        duree:
          type: integer
          description: Durée en minutes
          example: 148
        synopsis:
          type: string
          description: Résumé du film
        statut:
          type: string
          enum: [a_voir, vu, en_cours]
          description: Statut de visionnage
          default: "a_voir"
        note:
          type: number
          format: float
          minimum: 0
          maximum: 10
          description: Note personnelle sur 10
          example: 8.5
        commentaire:
          type: string
          description: Avis personnel sur le film
        affiche_url:
          type: string
          format: uri
          description: URL de l'affiche du film
        tmdb_id:
          type: integer
          description: ID The Movie Database (optionnel)
        tags:
          type: array
          items:
            type: string
          description: Tags personnalisés
          example: ["chef-d'oeuvre", "mindfuck"]

    Movie:
      allOf:
        - $ref: '#/components/schemas/MovieInput'
        - type: object
          required:
            - id
            - date_ajout
          properties:
            id:
              type: string
              description: Identifiant unique du film
              example: "507f1f77bcf86cd799439011"
            date_ajout:
              type: string
              format: date-time
              description: Date d'ajout à la collection
              example: "2024-03-15T14:30:00Z"
            date_visionnage:
              type: string
              format: date-time
              description: Date de visionnage (si statut = vu)
              example: "2024-03-20T20:00:00Z"

    Stats:
      type: object
      properties:
        total_films:
          type: integer
          description: Nombre total de films
          example: 127
        films_vus:
          type: integer
          description: Nombre de films vus
          example: 89
        films_a_voir:
          type: integer
          description: Nombre de films à voir
          example: 35
        films_en_cours:
          type: integer
          description: Nombre de films en cours
          example: 3
        note_moyenne:
          type: number
          format: float
          description: Note moyenne des films vus
          example: 7.8
        genres_preferes:
          type: array
          items:
            type: object
            properties:
              genre:
                type: string
              count:
                type: integer
          description: Top 5 des genres les plus présents
        duree_totale_visionnage:
          type: integer
          description: Durée totale de visionnage en minutes
          example: 13260

  parameters:
    pageParam:
      name: page
      in: query
      description: Numéro de page (commence à 0)
      required: false
      schema:
        minimum: 0
        type: integer
        format: int32
        default: 0
    limitParam:
      name: limit
      in: query
      description: Nombre maximum d'éléments par page
      required: false
      schema:
        maximum: 100
        minimum: 1
        type: integer
        format: int32
        default: 20